name: package-tests

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CKAN_HOST: ${{ secrets.CKAN_HOST }}
      CKAN_KEY: ${{ secrets.CKAN_KEY }}
      CKAN_HOST_PRODUCAO: ${{ secrets.CKAN_HOST_PRODUCAO }}
      CKAN_KEY_PRODUCAO: ${{ secrets.CKAN_KEY_PRODUCAO }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          python-version: '3.9'
      - run: pip install .
      - run: pip install -r requirements.txt
      - run: make coverage-xml
      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml   # coverage report